# Generated by Django 3.0.6 on 2020-05-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200526_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pos',
        ),
    ]
