# Generated by Django 3.0.6 on 2020-05-26 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('datecrea', models.DateField(db_column='dateCrea')),
                ('num_movie', models.ForeignKey(db_column='num_movie', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie')),
                ('num_user', models.ForeignKey(db_column='num_user', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.AuthUser')),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Pos',
        ),
    ]
