# Generated by Django 3.0.6 on 2020-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200526_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='idpost',
            field=models.AutoField(default='null', primary_key=True, serialize=False),
        ),
    ]
