# Generated by Django 3.0.6 on 2020-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200613_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idpost',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
