# Generated by Django 3.0.6 on 2020-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20200613_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idpost',
            field=models.AutoField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
