# Generated by Django 3.0.6 on 2020-06-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200618_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbooks',
            name='top1',
            field=models.ForeignKey(db_column='Top1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_content_type1', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='topbooks',
            name='top2',
            field=models.ForeignKey(db_column='Top2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_content_type2', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='topbooks',
            name='top3',
            field=models.ForeignKey(db_column='Top3', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_content_type3', to='movie.Movie'),
        ),
    ]
