# Generated by Django 3.0.6 on 2020-06-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20200619_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id_tops', models.AutoField(db_column='id_Tops', default='', editable=False, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(db_column='Book', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie')),
                ('top1', models.ForeignKey(db_column='Top1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topitype1', to='movie.Movie')),
                ('top2', models.ForeignKey(db_column='Top2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topictype', to='movie.Movie')),
                ('top3', models.ForeignKey(db_column='Top3', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topictype3', to='movie.Movie')),
            ],
            options={
                'db_table': 'top',
                'managed': True,
            },
        ),
    ]
